### ISSUE TITLE
[1.x] Build error when using older OpenSSL API

### ISSUE THREAD

**Issue by thebondo** [meetecho/janus-gateway#3622]
**What version of Janus is this happening on?**
1.4.0 commit aa86122

**Have you tested a more recent version of Janus too?**
Yes, the issue is also present in master branch commit da26c36

**Was this working before?**
Yes, building 1.3.0 worked

When updating a build using version 1.3.0 to use version 1.4.0, I ran into a build error.
```
dtls.c: In function 'janus_dtls_srtp_cleanup':
dtls.c:563:6: error: 'l' undeclared (first use in this function)
  for(l = 0; l < CRYPTO_num_locks(); l++) {
      ^
dtls.c:563:6: note: each undeclared identifier is reported only once for each function it appears in
dtls.c:1153:1: error: expected declaration or statement at end of input
 }
```
Line 563 was added in commit fd24309 [found here](https://github.com/meetecho/janus-gateway/blame/v1.4.0/src/dtls.c). The two added lines (563 and 564) use an undeclared variable l and are missing the closing brace for the if statement. Fixing these two issues makes the build work.

I am putting together a pull request to apply a fix, and should have it ready shortly.

**Comment by lminiero** [comment]
Good catch, and thanks for the PR!
