### PR TITLE
plugins/janus_audiobridge.c: fix build without libogg

### PR DESCRIPTION
**Pull request by ffontaine**
Build without libogg is broken since commit 53761d07c5456424d368c708fda2757e6606a4bf:

```
plugins/janus_audiobridge.c:1337:41: error: 'janus_audiobridge_participant' {aka 'struct janus_audiobridge_participant'} has no member named 'annc'
 1337 |  janus_audiobridge_file_free(participant->annc);
      |                                         ^~
  CC       plugins/plugins_libjanus_nosip_la-janus_nosip.lo
plugins/janus_audiobridge.c: In function 'janus_audiobridge_mixer_thread':
plugins/janus_audiobridge.c:6394:9: error: 'janus_audiobridge_participant' {aka 'struct janus_audiobridge_participant'} has no member named 'annc'
 6394 |     if(p->annc == NULL || g_atomic_int_get(&p->destroyed)) {
      |         ^~
plugins/janus_audiobridge.c:6398:16: warning: implicit declaration of function 'janus_audiobridge_file_read'; did you mean 'janus_audiobridge_mixer_thread'? [-Wimplicit-function-declaration]
 6398 |     int read = janus_audiobridge_file_read(p->annc, p->decoder, resampled, sizeof(resampled));
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                janus_audiobridge_mixer_thread
plugins/janus_audiobridge.c:6398:16: warning: nested extern declaration of 'janus_audiobridge_file_read' [-Wnested-externs]
plugins/janus_audiobridge.c:6398:45: error: 'janus_audiobridge_participant' {aka 'struct janus_audiobridge_participant'} has no member named 'annc'
 6398 |     int read = janus_audiobridge_file_read(p->annc, p->decoder, resampled, sizeof(resampled));
      |                                             ^~
plugins/janus_audiobridge.c:6401:10: error: 'janus_audiobridge_participant' {aka 'struct janus_audiobridge_participant'} has no member named 'annc'
 6401 |      if(p->annc->started) {
      |          ^~
plugins/janus_audiobridge.c:6428:10: error: 'janus_audiobridge_participant' {aka 'struct janus_audiobridge_participant'} has no member named 'annc'
 6428 |     if(!p->annc->started) {
      |          ^~
plugins/janus_audiobridge.c:6430:7: error: 'janus_audiobridge_participant' {aka 'struct janus_audiobridge_participant'} has no member named 'annc'
 6430 |      p->annc->started = TRUE;
      |       ^~
  CC       plugins/plugins_libjanus_streaming_la-janus_streaming.lo
```

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @ffontaine! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by lminiero** [comment]
Good catch, thanks! I see you've signed the CLA already, so I'll merge :+1:
