### PR TITLE
src/dtls-bio.h: fix build with libressl >= 3.5.0

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with libressl >= 3.5.0:

```
dtls-bio.c:40:1: error: variable 'janus_dtls_bio_agent_methods' has initializer but incomplete type
   40 | static BIO_METHOD janus_dtls_bio_agent_methods = {
      | ^~~~~~
```

Fixes:
 - http://autobuild.buildroot.org/results/92fe19446b40551c0139254d9efc6b3904fa287a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks for the fix! I'll copy it to the `0.x` branch as well :+1:
