### ISSUE TITLE
macos build with openssl@1.1

### ISSUE THREAD

**Issue by kazzmir** [meetecho/janus-gateway#1945]
Building janus 0.8.1 on macos 10.14 with openssl@1.1 installed via brew results in a configure error. I was able to manually get passed the configure error by adjusting PKG_CONFIG_PATH but then a compilation error occurs later on regarding openssl/rand.h not being found.

On macos typically openssl is installed into /usr/local/opt/openssl via `brew`. I'm not exactly sure how new openssl@1.1 is, but on my systems I only have /usr/local/opt/openssl@1.1 and do not have /usr/local/opt/openssl. Because of this, `configure` will throw an error out about libcrypto and libssl not being found.
```
$ ./configure
...
checking for
                    glib-2.0 >= 2.34
					libconfig
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                    zlib
                  ... no
configure: error: Package requirements (
                    glib-2.0 >= 2.34
					libconfig
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                    zlib
                  ) were not met:

No package 'libssl' found
No package 'libcrypto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

I added `/usr/local/opt/openssl@1.1/lib/pkgconfig` to my PKG_CONFIG_PATH, which makes configure happy, but then during the build with `make` I see
```
$ make V=1
libtool: compile:  gcc "-DPACKAGE_NAME=\"Janus WebRTC Server\"" -DPACKAGE_TARNAME=\"janus-gateway\" -DPACKAGE_VERSION=\"0.8.1\" "-DPACKAGE_STRING=\"Janus WebRTC Server 0.8.1\"" -DPACKAGE_BUGREPORT=\"https://github.com/meetecho/janus-gateway\" -DPACKAGE_URL=\"https://janus.conf.meetecho.com\" -DPACKAGE=\"janus-gateway\" -DVERSION=\"0.8.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PORTRANGE=1 -DHAVE_LIBNICE_TCP=1 -DHAVE_SRTP_2=1 -DHAVE_LIBCURL=1 -DHAVE_SAMPLEEVH=1 -DHAVE_RABBITMQEVH=1 -I. -I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/jansson/2.12/include -g -O2 -fPIC -fstack-protector-all -fstrict-aliasing -ggdb3 -pthread -Wall -Warray-bounds -Wextra -Wformat-nonliteral -Wformat-security -Wformat=2 -Winit-self -Winline -Wlarger-than=65537 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wno-aggregate-return -Wno-missing-field-initializers -Wno-redundant-decls -Wno-undef -Wno-unused-parameter -Wold-style-definition -Wpacked -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wswitch-default -Wunused -Wwrite-strings -Wcast-align -Wno-override-init -Wunsafe-loop-optimizations -Wunused-but-set-variable -I/usr/local/opt/openssl/include -I/usr/local/include -MT plugins/libjanus_nosip_la-janus_nosip.lo -MD -MP -MF plugins/.deps/libjanus_nosip_la-janus_nosip.Tpo -c plugins/janus_nosip.c  -fno-common -DPIC -o plugins/.libs/libjanus_nosip_la-janus_nosip.o
warning: unknown warning option '-Wno-override-init'; did you mean '-Wno-override-module'? [-Wunknown-warning-option]
warning: unknown warning option '-Wunsafe-loop-optimizations'; did you mean '-Wunavailable-declarations'? [-Wunknown-warning-option]
warning: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Wunknown-warning-option]
In file included from plugins/janus_nosip.c:168:
plugins/../rtpsrtp.h:18:10: fatal error: 'openssl/rand.h' file not found
#include <openssl/rand.h>
```
You can see that `-I/usr/local/opt/openssl/include` is in there, but `/usr/local/opt/openssl@1.1/include` is no where to be found. I think the reason for this is that configure.ac hardcodes the paths to openssl (and srtp)

configure.ac line ~79
```
case "$host_os" in
darwin*)
    CFLAGS="$CFLAGS -I/usr/local/opt/openssl/include -I/usr/local/include"
    # add rdynamic to LDFLAGS
    LDFLAGS="$LDFLAGS -Wl,-export_dynamic"
    LDFLAGS="$LDFLAGS -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/opt/local/lib -L/usr/local/libsrtp/lib"
    AM_CONDITIONAL([DARWIN_OS], true)
;;
```
Shouldn't these values come from `pkg-config libssl --cflags --libs` and `pkg-config srtp --cflags --libs`?

In any case, I finally worked around the problem by setting CFLAGS and LDFLAGS before running configure.
```
PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig \
CFLAGS="$CFLAGS -I/usr/local/opt/openssl@1.1/include" \
LDFLAGS="$LDFLAGS -L/usr/local/opt/openssl@1.1/lib"
```

I think an alternative workaround is just to symlink openssl@1.1 to openssl in /usr/local/opt, but I haven't tried this.

**Comment by lminiero** [comment]
Sorry, no idea as I don't build on Mac OS. Strictly speaking, we don't really support it: some people could get it compiled, and contributed lines to the README to explain how they did that. Sounds like this can be circumvented a couple of ways, so if you'd like to contribute changes to the README, we'll gladly review them (hoping other Mac OS users will validate it doesn't break it for them, though).

**Comment by felix-h** [comment]
I am seeing the same problem and agree that it would be good to use pkg-config to find the path to openssl. I am happy to validate a fix.

**Comment by felix-h** [comment]
FWIW, this is the linker error with OpenSSL 1.1

Undefined symbols for architecture x86_64:
  "_CRYPTO_THREADID_set_callback", referenced from:
      _janus_dtls_srtp_init in janus-dtls.o
  "_CRYPTO_THREADID_set_pointer", referenced from:
      _janus_dtls_cb_openssl_threadid in janus-dtls.o
  "_CRYPTO_num_locks", referenced from:
      _janus_dtls_srtp_init in janus-dtls.o
  "_CRYPTO_set_locking_callback", referenced from:
      _janus_dtls_srtp_init in janus-dtls.o
  "_ERR_free_strings", referenced from:
      _main in janus-janus.o
  "_EVP_cleanup", referenced from:
      _main in janus-janus.o
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      _main in janus-janus.o
  "_SSL_library_init", referenced from:
      _main in janus-janus.o
  "_SSL_load_error_strings", referenced from:
      _main in janus-janus.o
  "_SSL_state", referenced from:
      _janus_dtls_srtp_incoming_msg in janus-dtls.o

**Comment by kazzmir** [comment]
I saw those link errors as well, but that only seems to occur if janus is built with both -L/usr/local/opt/openssl and -L/usr/local/opt/openssl@1.1 (or maybe its the -I switches). Somehow one part of the library is built against one version of openssl and the final linking stage tries to use a different version. This problem is solved by only referring to the openssl@1.1 paths.

**Comment by lminiero** [comment]
If you guys can provide a fix to the README as a pull request that other Mac users can test and validate, I'll be glad to have a look at it and consider it for merging.

**Comment by kazzmir** [comment]
I attempted to modify the various autoconf/makefile stuff to get this to work properly but haven't had any luck yet. I suppose until a proper fix is implemented that the README can have a workaround, I'll make a PR in a bit.

**Comment by lminiero** [comment]
Any news on this? Since I'm personally not interested in whether this works on Mac OSX or not (we don't use it ourselves), I'll just close the issue if nobody provides a solution.

Thanks!

**Comment by 128keaton** [comment]
Hey, I just ran into a similar issue, first I was faced with the following:
```
ice.c:28:10: fatal error: 'stun/usages/bind.h' file not found
#include <stun/usages/bind.h>
         ^~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

I added the LDFLAGS/CFLAGS:
```
export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/libnice/lib"
export CFLAGS="$CFLAGS -I/opt/homebrew/opt/libnice/include"
```

Which got me further, then ran into openssl-related issue:
```
In file included from plugins/janus_sip.c:691:
plugins/../rtpsrtp.h:18:10: fatal error: 'openssl/rand.h' file not found
#include <openssl/rand.h>
         ^~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
```

Which lead me to add those paths to CFLAGS/LDFLAGS:
```
export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/libnice/lib -I/opt/homebrew/opt/opeenssl/lib"                                                                                                                                                                           
export CFLAGS="$CFLAGS -I/opt/homebrew/opt/libnice/include -I/opt/homebrew/opt/openssl/include"
```

That allowed me to compile successfully on macOS Sonoma

**Comment by psharrma** [comment]
Any 1 who is still struggling, with latest commit in the repo there is minor change to CFLAGS/LDFLAGS over the one suggested by @128keaton :

`export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/libnice/lib -I/opt/homebrew/opt/opeenssl/lib -I/opt/homebrew/Cellar/opus/1.5.2/lib"
export CFLAGS="$CFLAGS -I/opt/homebrew/opt/libnice/include -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/Cellar/opus/1.5.2/include"`
