### ISSUE TITLE
Doesn't build with libwebsockets > 4.0

### ISSUE THREAD

**Issue by ssalenik** [meetecho/janus-gateway#2630]
```
transports/janus_websockets.c:535:12: error: no member named 'ws_ping_pong_interval' in 'struct lws_context_creation_info'
                        wscinfo.ws_ping_pong_interval = pingpong_trigger;
                        ~~~~~~~ ^
20 warnings and 1 error generated.
make[2]: *** [transports/libjanus_websockets_la-janus_websockets.lo] Error 1
make[1]: *** [all-recursive] Error 1
```

libwebsockets changed ping-pong behaviour to be automatic in 4.0:
https://github.com/warmcat/libwebsockets/blob/main/changelog#L125-L127

And then removed the `ws_ping_pong_interval` in this commit:
https://github.com/warmcat/libwebsockets/commit/280c81278dcb88c074aa19cbf8de809e366a9ece

Also, v 2.4.1 doesn't work well on macos, so maybe should add a comment to the readme about suggested version(s) here:
https://github.com/meetecho/janus-gateway/blame/master/README.md#L25

But possibly also should add a check in configure?

I could make a PR for either, depending on what makes sense.

**Comment by ssalenik** [comment]
Oups, sorry, saw that this is already accounted for in the latest version. I was on an older one.
